### ISSUE TITLE
KafkaWriter fails to write data for boolean types

### ISSUE THREAD

**Issue by DanWertheimer** [AbsaOSS/py2k#44]
### Checks

- [x] I added a descriptive title to this issue
- [x] I have searched (google, github) for similar issues and couldn't find anything

# Bug

- py2k version: `1.8.0`
- Python version: `3.9`
- Operating System: `MacOS`

## Expected Result

```py
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 10.09it/s]
```

## Actual Result

```py
Traceback (most recent call last):
  File "/examples/basic_write_from_pandas.py", line 25, in <module>
    writer.write(records)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/py2k-1.8.0-py3.9.egg/py2k/writer.py", line 57, in write
    self._create_producer(records)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/py2k-1.8.0-py3.9.egg/py2k/writer.py", line 49, in _create_producer
    self._producer = KafkaProducer(self._topic, producer_config)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/py2k-1.8.0-py3.9.egg/py2k/producer.py", line 22, in __init__
    self._producer = SerializingProducer(producer_config.dict)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/py2k-1.8.0-py3.9.egg/py2k/producer_config.py", line 35, in dict
    config_build['value.serializer'] = self._serializer.value_serializer()
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/py2k-1.8.0-py3.9.egg/py2k/serializer.py", line 31, in value_serializer
    return AvroSerializer(
  File "/folder/anaconda3/envs/py2k/lib/python3.9/site-packages/confluent_kafka/schema_registry/avro.py", line 174, in __init__
    schema_dict = loads(schema.schema_str)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/folder/anaconda3/envs/py2k/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/folder/anaconda3/envs/py2k/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 158 (char 157)
```

### Code Snippet

```py
from py2k.record import PandasToRecordsTransformer
from py2k.writer import KafkaWriter
import pandas as pd


df = pd.DataFrame({'name': ['Daniel', 'David', 'Felipe', 'Ruslan'],
                   'is_cool': [False, True, True, True],
                   'value': [27.1, 100.0, 0, 9000.0]})

record_transformer = PandasToRecordsTransformer(
    df, record_name='KafkaRecord')

records = record_transformer.from_pandas()


topic = 'py2k-test-topic'
producer_config = {'bootstrap.servers': '...'}
schema_registry_config = {
    'url': '...'}

writer = KafkaWriter(topic=topic,
                     schema_registry_config=schema_registry_config,
                     producer_config=producer_config)

writer.write(records)

```

##

**Comment by DanWertheimer** [comment]
Problem is related to schema generation of boolean types:

`{"default": False, "type": "boolean", "name": "is_cool"}`

default of `False` should not be capitalised for Avro.
